create table roles(
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table users(
    id int8 generated by default as identity,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    primary key (id)
);

create table users_roles(
    user_id int8 not null,
    role_id int8 not null
);

alter table if exists roles add constraint UK_unique_role_name_constraint unique (name);
alter table if exists users add constraint UK_unique_user_email unique (email);
alter table if exists users_roles add constraint FK_roles_foreign_key foreign key (role_id) references roles;
alter table if exists users_roles add constraint FK_users_foreign_key foreign key (user_id) references users;

insert into roles (name) values
('ROLE_ADMIN'),
('ROLE_USER'),
('ROLE_OWNER');


insert into users (email, first_name, last_name, password) values
('m@mail.ru', 'Matt', 'Lazarev', '$2a$10$m31UOa0EypUcnzt4UCHEIOQjrgtHj5eWT4CSOO9v2vcPjByP7lAeC'),
('b@mail.ru', 'Bob', 'Tyson', '$2a$10$4apR0fQlH6J5pKC9ZsCbXuu9hMRZmY2uek/uXvXnkPJSCmVm8UGCe');

insert into users_roles values
(1, 1), (1, 2), (1, 3), (2, 2);